{"uid":"51324dabb021b033","name":"test_login_in_several_times","fullName":"test_login_page.TestLogin#test_login_in_several_times","historyId":"72b38e43aa324f8bd9e2c49ef06620cb","time":{"start":1721031286268,"stop":1721031293462,"duration":7194},"status":"failed","statusMessage":"AssertionError: The error message is not the same as expected.\nassert 'Invalid user...se try again.' == 'You have use...r 15 minutes.'\n  \n  - You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.\n  + Invalid username or password. Please try again.","statusTrace":"self = <tests.test_login_page.TestLogin object at 0x0000010C63220310>\n\n    def test_login_in_several_times(self):\n        self.driver_manager.open_railway_page()\n        driver = self.driver_manager.get_driver()\n        base_page = BasePage(driver)\n        base_page.open_login_tab()\n        login_page = LoginPage(driver)\n    \n        login_page.login_several_time(user_invalid, 4)\n        actual_msg = login_page.get_error_msg()\n        expected_msg = \"You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.\"\n>       assert actual_msg == expected_msg, \"The error message is not the same as expected.\"\nE       AssertionError: The error message is not the same as expected.\nE       assert 'Invalid user...se try again.' == 'You have use...r 15 minutes.'\nE         \nE         - You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.\nE         + Invalid username or password. Please try again.\n\ntest_login_page.py:66: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup_and_teardown","time":{"start":1721031284861,"stop":1721031286268,"duration":1407},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: The error message is not the same as expected.\nassert 'Invalid user...se try again.' == 'You have use...r 15 minutes.'\n  \n  - You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.\n  + Invalid username or password. Please try again.","statusTrace":"self = <tests.test_login_page.TestLogin object at 0x0000010C63220310>\n\n    def test_login_in_several_times(self):\n        self.driver_manager.open_railway_page()\n        driver = self.driver_manager.get_driver()\n        base_page = BasePage(driver)\n        base_page.open_login_tab()\n        login_page = LoginPage(driver)\n    \n        login_page.login_several_time(user_invalid, 4)\n        actual_msg = login_page.get_error_msg()\n        expected_msg = \"You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.\"\n>       assert actual_msg == expected_msg, \"The error message is not the same as expected.\"\nE       AssertionError: The error message is not the same as expected.\nE       assert 'Invalid user...se try again.' == 'You have use...r 15 minutes.'\nE         \nE         - You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.\nE         + Invalid username or password. Please try again.\n\ntest_login_page.py:66: AssertionError","steps":[],"attachments":[{"uid":"4c1af2ef6a9f357f","name":"screenshot","source":"4c1af2ef6a9f357f.png","type":"image/png","size":651436}],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":true,"attachmentsCount":1,"shouldDisplayMessage":true},"afterStages":[{"name":"setup_and_teardown::0","time":{"start":1721031293751,"stop":1721031295888,"duration":2137},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('setup_and_teardown')"},{"name":"suite","value":"test_login_page"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"TUYETNHI"},{"name":"thread","value":"2268-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_login_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('setup_and_teardown')"]},"source":"51324dabb021b033.json","parameterValues":[]}