{"uid":"8a11fd034d855194","name":"test_login_with_invalid_password","fullName":"test_login_page.TestLogin#test_login_with_invalid_password","historyId":"80d66add323cb88597efd043a6af3f3c","time":{"start":1721031277785,"stop":1721031282443,"duration":4658},"status":"failed","statusMessage":"AssertionError: The error message is not the same as expected.\nassert 'Invalid user...se try again.' == 'There was a ...in your form.'\n  \n  - There was a problem with your login and/or errors exist in your form.\n  + Invalid username or password. Please try again.","statusTrace":"self = <tests.test_login_page.TestLogin object at 0x0000010C63217B90>\n\n    def test_login_with_invalid_password(self):\n        self.driver_manager.open_railway_page()\n        driver = self.driver_manager.get_driver()\n        base_page = BasePage(driver)\n        base_page.open_login_tab()\n        login_page = LoginPage(driver)\n        login_page.submit_login_form(user_invalid)\n        actual_msg = login_page.get_error_msg()\n        expected_msg = \"There was a problem with your login and/or errors exist in your form.\"\n>       assert actual_msg == expected_msg, \"The error message is not the same as expected.\"\nE       AssertionError: The error message is not the same as expected.\nE       assert 'Invalid user...se try again.' == 'There was a ...in your form.'\nE         \nE         - There was a problem with your login and/or errors exist in your form.\nE         + Invalid username or password. Please try again.\n\ntest_login_page.py:54: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"setup_and_teardown","time":{"start":1721031272187,"stop":1721031277784,"duration":5597},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: The error message is not the same as expected.\nassert 'Invalid user...se try again.' == 'There was a ...in your form.'\n  \n  - There was a problem with your login and/or errors exist in your form.\n  + Invalid username or password. Please try again.","statusTrace":"self = <tests.test_login_page.TestLogin object at 0x0000010C63217B90>\n\n    def test_login_with_invalid_password(self):\n        self.driver_manager.open_railway_page()\n        driver = self.driver_manager.get_driver()\n        base_page = BasePage(driver)\n        base_page.open_login_tab()\n        login_page = LoginPage(driver)\n        login_page.submit_login_form(user_invalid)\n        actual_msg = login_page.get_error_msg()\n        expected_msg = \"There was a problem with your login and/or errors exist in your form.\"\n>       assert actual_msg == expected_msg, \"The error message is not the same as expected.\"\nE       AssertionError: The error message is not the same as expected.\nE       assert 'Invalid user...se try again.' == 'There was a ...in your form.'\nE         \nE         - There was a problem with your login and/or errors exist in your form.\nE         + Invalid username or password. Please try again.\n\ntest_login_page.py:54: AssertionError","steps":[],"attachments":[{"uid":"30796b4a971d5c69","name":"screenshot","source":"30796b4a971d5c69.png","type":"image/png","size":650613}],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":true,"attachmentsCount":1,"shouldDisplayMessage":true},"afterStages":[{"name":"setup_and_teardown::0","time":{"start":1721031282718,"stop":1721031284856,"duration":2138},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentStep":false,"hasContent":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('setup_and_teardown')"},{"name":"suite","value":"test_login_page"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"TUYETNHI"},{"name":"thread","value":"2268-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_login_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["@pytest.mark.usefixtures('setup_and_teardown')"]},"source":"8a11fd034d855194.json","parameterValues":[]}